name: Terraform CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    name: Run Terraform Validation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 3: Terraform fmt (to check formatting)
      - name: Run terraform fmt
        run: terraform fmt -check -recursive

      # Step 4: Terraform validate (to check syntax)
      - name: Run terraform validate
        run: terraform validate
