name: Terraform CI

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform:
    name: Run Terraform Validation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 3: Check if Terraform files are formatted correctly
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Replace set-output (Use Environment Files)
      - name: Set environment variable
        run: echo "name=terraform_output::value" >> $GITHUB_ENV
